name: 'CYF Tune In Radio Automation Script'
description:
  'Automated script to assist with the updating of the playlist from the Tune in
  Radio Project'
author: 'Man Sang Sin'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
